services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated    # monta solo tu código
      - /app/node_modules   # preserva node_modules del contenedor
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true